import Head from "next/head";
import { Input, Flex, Stack, Text, Link, Button } from "@chakra-ui/react";
import { useRouter } from "next/router";
import { Logo } from "../components/Logo";
import Image from "next/image";
import { getTopics } from "../api/getTopics";

function Login() {
  const router = useRouter();

  getTopics().then(console.log);
  return (
    <>
      <Head>
        <title>HiStory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack w="100%" px="128px" py="128px" bg="white">
        <Flex flexDir="column" w="400px" mb="25px">
          <Logo />
          <Text fontSize="16px" opacity="40%">
            Historia pisze się sama
          </Text>
        </Flex>

        <Image src="/soldier.png" alt="soldier" width="300" height="500" />

        <Flex justifyContent="space-between">
          <Stack spacing="10px">
            <Input placeholder="login" />
            <Input placeholder="hasło" type="password" />

            <Button
              onClick={() => {
                router.push("/topics");
              }}
            >
              zaloguj
            </Button>
          </Stack>
          <Flex
            w="300px"
            alignSelf="flex-end"
            justifySelf="flex-end"
            flexDir="column"
          >
            <Text opacity="40%" mb="5px" alignSelf="center">
              Projekt możliwy dzięki
            </Text>
            <Link href="https://ipn.gov.pl" isExternal>
              <Image src="/ipn.jpg" alt="soldier" width="500" height="200" />
            </Link>
          </Flex>
        </Flex>
      </Stack>
    </>
  );
}

export default Login;
