import Head from "next/head";
import { useQuiz } from "../hooks/useQuiz";
import { Login } from "./login";

export default function Home() {
  const query = useQuiz();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
  );
}
